# Generated by Django 4.0.2 on 2022-02-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_image_product_image1_product_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image',
        ),
    ]
